/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ituriel_liebes
 */
public class EventForm extends javax.swing.JFrame {
    private Agenda agenda;
    private java.util.List<Person> contacts;
    private DefaultComboBoxModel<String> contactModel;
    /**
     * Creates new form EventForm
     */
    public EventForm(Agenda agenda, java.util.List<Person> contacts) {
        initComponents();
        this.agenda = agenda;
        this.contacts = contacts;
        
        contactModel = new DefaultComboBoxModel<>();
        listaContactos.setModel(contactModel);
        updateContactList();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /**
     * Funciones necesarias para que la gui funcione:
     */
    private void updateContactList() {
        contactModel.removeAllElements();
        for (Person p : contacts) {
            contactModel.addElement(p._toString());
        }
    }
    private void limpiarCampos() {
    entryDia.setText("dd");
    entryMes.setText("mm");
    entryAnn.setText("yyyy");
    entryHoraIn.setText("00");
    entryMinIn.setText("00");
    entrySecIn.setText("00");
    entryHoraFin.setText("00");
    entryMinFin.setText("00");
    entrySecFin.setText("00");
    desc.setText("");
    listaContactos.setSelectedIndex(-1);  // Deseleccionar el contacto
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listaContactos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        entryDia = new javax.swing.JTextField();
        entryMes = new javax.swing.JTextField();
        entryAnn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        entryHoraIn = new javax.swing.JTextField();
        entryMinIn = new javax.swing.JTextField();
        entrySecIn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        entryHoraFin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        entryMinFin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        entrySecFin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        crear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Creacion de evento");

        jLabel2.setText("Contacto:");

        jLabel3.setText("Fecha:");

        entryDia.setText("dd");

        entryMes.setText("mm");

        entryAnn.setText("yyyy");
        entryAnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryAnnActionPerformed(evt);
            }
        });

        jLabel4.setText("Hora Inicio:");

        entryHoraIn.setText("00");

        entryMinIn.setText("00");

        entrySecIn.setText("00");

        jLabel5.setText(":");

        jLabel6.setText(":");

        jLabel7.setText("Hora Final:");

        entryHoraFin.setText("00");

        jLabel8.setText(":");

        entryMinFin.setText("00");

        jLabel9.setText(":");

        entrySecFin.setText("00");

        jLabel10.setText("Descripcion:");

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(entryDia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(entryMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(entryAnn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(listaContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(entryHoraIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel5)
                                        .addGap(10, 10, 10)
                                        .addComponent(entryMinIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(entrySecIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(entryHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel8)
                                        .addGap(10, 10, 10)
                                        .addComponent(entryMinFin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(entrySecFin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(crear))
                        .addGap(18, 18, 18)
                        .addComponent(desc)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(listaContactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(entryDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryAnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(entryHoraIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryMinIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrySecIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(entryHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryMinFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrySecFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void entryAnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryAnnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryAnnActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
        try {
            // Validar que se haya seleccionado un contacto
            int contactoSeleccionado = listaContactos.getSelectedIndex();
            if (contactoSeleccionado == -1) {
                JOptionPane.showMessageDialog(this, "Por favor, selecciona un contacto.");
                return;
            }

            Person contacto = contacts.get(contactoSeleccionado);  // Obtener el contacto seleccionado

            // Validar fecha (dd, mm, aaaa)
            int dia = Integer.parseInt(entryDia.getText());
            int mes = Integer.parseInt(entryMes.getText());
            int anno = Integer.parseInt(entryAnn.getText());
            Date fecha = new Date(anno, mes, dia);  // Crear el objeto Date con los valores ingresados

            // Validar horas (hora, minuto, segundo)
            int horaIn = Integer.parseInt(entryHoraIn.getText());
            int minIn = Integer.parseInt(entryMinIn.getText());
            int segIn = Integer.parseInt(entrySecIn.getText());
            Time horaInicio = new Time(horaIn, minIn, segIn);

            int horaFin = Integer.parseInt(entryHoraFin.getText());
            int minFin = Integer.parseInt(entryMinFin.getText());
            int segFin = Integer.parseInt(entrySecFin.getText());
            Time horaFinal = new Time(horaFin, minFin, segFin);

            // Obtener la descripción del evento
            String descripcion = desc.getText();

            // Crear el objeto Event
            Event evento = new Event(
                "Evento con " + contacto.getName(),  // Asunto del evento
                descripcion,                         // Descripción
                contacto,                            // Persona asociada al evento
                fecha,                               // Fecha del evento
                horaInicio,                          // Hora de inicio
                horaFinal                            // Hora de finalización
            );

            // Añadir el evento a la agenda
            agenda.addEvent(evento);
            this.dispose();
            // Confirmación de que el evento se creó correctamente
            JOptionPane.showMessageDialog(this, "Evento creado exitosamente.");

            // Limpiar los campos
            limpiarCampos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa números válidos para la fecha y la hora.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al crear el evento.");
        }
    }//GEN-LAST:event_crearActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crear;
    private javax.swing.JTextField desc;
    private javax.swing.JTextField entryAnn;
    private javax.swing.JTextField entryDia;
    private javax.swing.JTextField entryHoraFin;
    private javax.swing.JTextField entryHoraIn;
    private javax.swing.JTextField entryMes;
    private javax.swing.JTextField entryMinFin;
    private javax.swing.JTextField entryMinIn;
    private javax.swing.JTextField entrySecFin;
    private javax.swing.JTextField entrySecIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> listaContactos;
    // End of variables declaration//GEN-END:variables
}
